#!/bin/bash

# establish video url as variable to be used in the script.
url=$1
# request youtube-dl to get video title and store it in a variable named title!
title=$(youtube-dl "$url" --get-title)

# Replace spaces in title of the video name so that the mkdir won't have diffeculty making the directory!
title1=${title// /_}

# Store original location for later use!
original_location=$(pwd)

# Make a directory for the video.
mkdir $(pwd)/$title1

# change directory into the directory stored in the string $title1!
cd $title1

# Download the video into "PWD/$title1 
youtube-dl -r 10M -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio' --merge-output-format mp4 --embed-thumbnail --add-metadata -o '%(title)s.%(ext)s' $url

# time to get back to original location in case the user runs the script again!
cd $original_location

echo 'You can find your video in' $title1
